### ISSUE TITLE
希望支持“智能修复”清晰度

### ISSUE THREAD

**Issue by 123wanshuaya** [ScottSloan/Bili23-Downloader#10]
![image](https://github.com/user-attachments/assets/5ce69d41-2b38-4662-aa2b-7b5c1da25a2b)
（eg：https://www.bilibili.com/bangumi/play/ep65413  中有“智能修复”清晰度）
希望支持该清晰度

**Comment by ScottSloan** [comment]
目前正在研究，将在1.43版本中支持

**Comment by ScottSloan** [comment]
目前已经支持下载智能修复清晰度的视频，将随1.43版本发布，请留意更新
