### ISSUE TITLE
fix:  视频合并失败

### ISSUE THREAD

**Issue by Gmakter** [ScottSloan/Bili23-Downloader#13]
url: https://www.bilibili.com/bangumi/play/ss33435
分辨率： 杜比视界
错误信息：
ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband  libavutil      59.  8.100 / 59.  8.100  libavcodec     61.  3.100 / 61.  3.100  libavformat    61.  1.100 / 61.  1.100  libavdevice    61.  1.100 / 61.  1.100  libavfilter    10.  1.100 / 10.  1.100  libswscale      8.  1.100 /  8.  1.100  libswresample   5.  1.100 /  5.  1.100  libpostproc    58.  1.100 / 58.  1.100Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video_6907.mp4':  Metadata:    major_brand     : mp42    minor_version   : 1    compatible_brands: mp42dby1iso5    creation_time   : 2021-07-13T04:45:14.000000Z  Duration: 01:38:10.33, start: 0.083333, bitrate: 8014 kb/s  Stream #0:0[0x1](und): Video: hevc (Main 10) (dvh1 / 0x31687664), yuv420p10le(pc), 3840x1600 [SAR 1:1 DAR 12:5], 2 kb/s, 24 fps, 24 tbr, 24 tbn (default)      Metadata:        handler_name    : Bento4 Video Handler        vendor_id       : [0][0][0][0]        encoder         : DOVI Coding      Side data:        DOVI configuration record: version: 1.0, profile: 5, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0[in#1 @ 000001c860f83180] Error opening input: No such file or directoryError opening input file audio_6907.None.Error opening input files: No such file or directory

![image](https://github.com/user-attachments/assets/a40da2d0-30b6-47a5-8f98-fd011755ff7e)

**Comment by ScottSloan** [comment]
在我这里测试没有任何问题

**Comment by Gmakter** [comment]
![444b4001c7ddcebc9b7ec35332d922dc](https://github.com/user-attachments/assets/6313fa00-45a9-4a66-af7e-1c497ce58e2b)
调试出这样的一个报错   然后下载管理就会一直显示 “正在合成视频”  并不会提示报错

**Comment by RChips22** [comment]
我也遇到了这个问题，但看起来似乎不是格式丢失，而是类似格式化错误或者文件路径错误，错误信息如下
ffmpeg version 2024-09-16-git-76ff97cef5-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint  libavutil      59. 36.100 / 59. 36.100  libavcodec     61. 13.100 / 61. 13.100  libavformat    61.  5.101 / 61.  5.101  libavdevice    61.  2.101 / 61.  2.101  libavfilter    10.  2.102 / 10.  2.102  libswscale      8.  2.100 /  8.  2.100  libswresample   5.  2.100 /  5.  2.100  libpostproc    58.  2.100 / 58.  2.100[in#0 @ 000001c720d2b5c0] Error opening input: No such file or directoryError opening input file video_3711.mp4.Error opening input files: No such file or directory

**Comment by ScottSloan** [comment]
可能是下载目录含有空格导致的问题，目前已经修复，随下个版本更新

**Comment by RChips22** [comment]
> 可能是下载目录含有空格导致的问题，目前已经修复，随下个版本更新

我试图直接从源码版本中启动GUI.py，但是在下载时遇到了和Gmakter一样的错误（合成出错但是不报错）
Python报告了如下错误（download.py,757 行)
AttributeError: 'DownloadUtils' object has no attribute 'merge_error_log'. Did you mean: 'merge_error'?

**Comment by ScottSloan** [comment]
dev 分支已经修复了这个问题，可以先克隆 dev分支试试

**Comment by RChips22** [comment]
> dev 分支已经修复了这个问题，可以先克隆 dev分支试试

克隆了dev分支进行测试，这些问题看起来都已经修复了。
