### ISSUE TITLE
问题：无法解析（僅限港澳台地區）之番剧

### ISSUE THREAD

**Issue by Aussstin** [ScottSloan/Bili23-Downloader#20]
无论是否使用vpn，当解析（僅限港澳台地區）类番剧链接时均提示“解析失败：链接不存在”，目前已尝试并失败的链接如下：
https://www.bilibili.com/bangumi/play/ss40713
https://www.bilibili.com/bangumi/play/ss44958
https://www.bilibili.com/bangumi/play/ss21680
https://www.bilibili.com/bangumi/play/ss42082

**Comment by ScottSloan** [comment]
可在设置中开启代理，如图所示：
[![pA3J40J.png](https://s21.ax1x.com/2024/10/01/pA3J40J.png)](https://imgse.com/i/pA3J40J)

经测试能正常识别：
[![pA3J579.png](https://s21.ax1x.com/2024/10/01/pA3J579.png)](https://imgse.com/i/pA3J579)

程序目前暂时不能使用系统代理，需要在设置中手动设置，后续会进行优化。

**Comment by Aussstin** [comment]
谢谢！刚刚再次尝试，确实解析成功
