### ISSUE TITLE
mac下点击登陆的时候提示缺少PIL的库

### ISSUE THREAD

**Issue by SevenDreamer** [ScottSloan/Bili23-Downloader#21]
![image](https://github.com/user-attachments/assets/5ef23f01-0155-4984-a875-715ea66ca70d)

**Comment by ScottSloan** [comment]
安装 qrcode 库时会顺带一起安装的，看一下有没有安装 qrcode，要靠这个库生成二维码

**Comment by ImYrS** [comment]
> 安装 qrcode 库时会顺带一起安装的
@ScottSloan 这个实测 macOS 上没有一起安装。
需要单独执行一次 `pip install Pillow`。感觉可以考虑加到 requirements 文件中。

macOS 15.0 (24A335)
Python 3.11.3

**Comment by ScottSloan** [comment]
> > 安装 qrcode 库时会顺带一起安装的
> @ScottSloan 这个实测 macOS 上没有一起安装。
> 需要单独执行一次 `pip install Pillow`。感觉可以考虑加到 requirements 文件中。
> 
> macOS 15.0 (24A335)
> Python 3.11.3

感谢反馈，已经添加进 requirements.txt 中
