### ISSUE TITLE
问题：无法解析大部分番剧、电影、纪录片

### ISSUE THREAD

**Issue by wwwwwwow** [ScottSloan/Bili23-Downloader#23]
账号是大会员并且已经登陆，但在解析大部分番剧、电影、纪录片时会报出解析失败：无法获取视频信息，请登录后再试。
连使用说明里的实例链接 https://www.bilibili.com/bangumi/play/ss45574 也同样无法解析。

**Comment by IvanHanloth** [comment]
经过测试没有出现同样的这样的情况。
![image](https://github.com/user-attachments/assets/a42e7b9b-84a6-4a27-aa76-d67797aa1e7c)

可能由于网络波动导致或代理配置错误等情况导致，建议检查相关配置

**Comment by wwwwwwow** [comment]
那应该是因为人不在国内，请问如果人在欧洲地区该怎么解决

**Comment by ScottSloan** [comment]
请在设置中开启代理功能，配合代理软件使用

**Comment by IvanHanloth** [comment]
尝试前往“工具”->"设置"->"代理"处启用并国内代理

**Comment by wwwwwwow** [comment]
感谢，已解决
