### ISSUE TITLE
无法下载番剧《胆大党》

### ISSUE THREAD

**Issue by henyuer** [ScottSloan/Bili23-Downloader#26]
[
![屏幕截图 2024-10-19 002715](https://github.com/user-attachments/assets/972f37ed-ee49-45f0-94f3-50be056fd01f)
](url)
如图，新番《胆大党》无法下载，普通视频可以下载

**Comment by ScottSloan** [comment]
请先登录自己的大会员账号，本程序不提供会员视频免费解析功能。

**Comment by henyuer** [comment]
确实可以了，速度很快
![屏幕截图 2024-10-22 001133](https://github.com/user-attachments/assets/6dc62aae-8320-40d7-b5ba-fb1cc18042dc)
