### ISSUE TITLE
合成视频有概率失败

### ISSUE THREAD

**Issue by souloftouch** [ScottSloan/Bili23-Downloader#36]
![image](https://github.com/user-attachments/assets/384e21e2-21fb-49f1-80c9-452bd4625bd3)
合成视频时有时会出现合成失败的情况，报错如下

ffmpeg version 7.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband  libavutil      59.  8.100 / 59.  8.100  libavcodec     61.  3.100 / 61.  3.100  libavformat    61.  1.100 / 61.  1.100  libavdevice    61.  1.100 / 61.  1.100  libavfilter    10.  1.100 / 10.  1.100  libswscale      8.  1.100 /  8.  1.100  libswresample   5.  1.100 /  5.  1.100  libpostproc    58.  1.100 / 58.  1.100Unrecognized option 'INTERGALACTIA- 閾剁嫾.mp4'.Error splitting the argument list: Option not found

**Comment by ScottSloan** [comment]
已经修复了，报错原因是ffmpeg 把 `-` 开头的文件名当成了参数。

**Comment by souloftouch** [comment]
![image](https://github.com/user-attachments/assets/e716b639-15c8-4c82-af9e-fe93a1bf5324)
但是看了下我应该用的是最新的版本吧（虽然版本号好像显示的不对）

**Comment by ScottSloan** [comment]
dev 分支中已经修复了，可以手动安装，编译版只随大版本更新发布。

**Comment by souloftouch** [comment]
ok
