### ISSUE TITLE
下载完成后两个文件消失

### ISSUE THREAD

**Issue by ChinaIceF** [ScottSloan/Bili23-Downloader#4]
如题，下载过程中生成视频文件和音频文件，在下载完成的时候，没有新文件生成，并且上述两个文件直接消失。已经关闭Windows Defender，更换过python环境，问题仍然没有解决
请检查这是否源于ffmpeg的调用错误，谢谢
我的平台 Windows 11 22H2，python 3.10.4

**Comment by ScottSloan** [comment]
此问题源于 ffmpeg 检测问题，将 ffmpeg 添加至环境变量即可暂时解决。您也可以更新至 1.40 版本，已对前版本遗留bug进行了修复。

**Comment by africa1207** [comment]
> 此问题源于 ffmpeg 检测问题，将 ffmpeg 添加至环境变量即可暂时解决。您也可以更新至 1.40 版本，已对前版本遗留bug进行了修复。

win11，使用的1.4.1，ffmpeg配置了，下载大会员番剧下载过程中有视频和音频，最后合并后直接丢失
![image](https://github.com/ScottSloan/Bili23-Downloader/assets/21698755/640ec723-49dd-4568-b4ae-e332386a2235)

**Comment by ScottSloan** [comment]
> > 此问题源于 ffmpeg 检测问题，将 ffmpeg 添加至环境变量即可暂时解决。您也可以更新至 1.40 版本，已对前版本遗留bug进行了修复。
> 
> win11，使用的1.4.1，ffmpeg配置了，下载大会员番剧下载过程中有视频和音频，最后合并后直接丢失
> ![image](https://github.com/ScottSloan/Bili23-Downloader/assets/21698755/640ec723-49dd-4568-b4ae-e332386a2235)
> 

请问具体是哪一部番剧呢，麻烦给一个链接，方便排查问题

**Comment by africa1207** [comment]
> > > 此问题源于 ffmpeg 检测问题，将 ffmpeg 添加至环境变量即可暂时解决。您也可以更新至 1.40 版本，已对前版本遗留bug进行了修复。
> > 
> > 
> > win11，使用的1.4.1，ffmpeg配置了，下载大会员番剧下载过程中有视频和音频，最后合并后直接丢失
> > ![image](https://private-user-images.githubusercontent.com/21698755/326224794-640ec723-49dd-4568-b4ae-e332386a2235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTcyOTQsIm5iZiI6MTcxNDM1Njk5NCwicGF0aCI6Ii8yMTY5ODc1NS8zMjYyMjQ3OTQtNjQwZWM3MjMtNDlkZC00NTY4LWI0YWUtZTMzMjM4NmEyMjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NTliNjIzMDZkZjJkMWNkOGJjYjE0N2Y5NGM1OWRiNDBiZGM0M2E4OTEyYzRhNDZkM2IzOGVhMWQ1NTE3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fOe_YOrV5GTfwgqYCNaU9_cQAURUBcmZWQT7NKrO678)
> 
> 请问具体是哪一部番剧呢，麻烦给一个链接，方便排查问题

https://www.bilibili.com/bangumi/play/ss47641?from_spmid=666.25.series.0
