### ISSUE TITLE
经测试修改部分代码后可以在mac上运行，但核心代码大量使用windll模块不兼容mac

### ISSUE THREAD

**Issue by hyrulelinks** [ScottSloan/Bili23-Downloader#8]
经测试修改部分代码后可以在mac上运行（指打开主界面），但核心代码大量使用windll模块不兼容mac

因此下载无法生效，另外mac下ffmpeg没有exe后缀，主程序也找不到ffmpeg，建议作者兼容下mac设备

**Comment by ScottSloan** [comment]
你好，当前版本仅支持 Windows，关于跨平台支持（含Linux，macOS）已在计划中，请关注后续开发进展。
